### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Hashiguchi0828** [Hashiguchi0828/furima-38564#26]
# 自身のフリマアプリのURL
https://ajax-app-furima-38564.herokuapp.com/
# Basic認証のIDとパスワード
ID                  admin
パスワード　2222
# 出品者用のメールアドレスとパスワード
メールアドレス　　　test1@test
パスワード　　　　　test0000
# 購入者用のメールアドレスとパスワード
メールアドレス　　　test2@test
パスワード　　　　　test0000

**Comment by motomuun** [comment]
@Hashiguchi0828 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
「新品"、"未使用」「未使用"品"に近い」となっております。””で囲っているところを正しいものに修正お願いします。

- [ ] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
「送料"払い"」となっております。""で囲っているところを正しいものに修正お願いします。

**商品編集機能の確認**

- [ ] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
自身が出品していない商品の編集ページへ遷移しようとすると、下記エラーページに遷移します。トップページに遷移出来るように修正をお願いします。
<img width="1439" alt="スクリーンショット 2022-10-26 10 53 13" src="https://user-images.githubusercontent.com/65059944/197916083-479f1a1d-dfc8-42c8-b421-65f93aca1df9.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Hashiguchi0828** [comment]
修正しました

**Comment by Hashiguchi0828** [comment]
修正しました

**Comment by motomuun** [comment]
@Hashiguchi0828 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/65059944/197931157-01fdf2b6-20c8-4b91-9c75-a54319065d72.png)
